# -*- coding: utf-8 -*-
"""Firedetection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFBaue-OGJS6bEnM5JZOBy69j_TWDC5U
"""

!nvidia-smi

!pip install ultralytics

from ultralytics import YOLO

!yolo task = detect mode = train model = yolov8n.pt data = /content/drive/MyDrive/data/data.yaml epochs = 1 imgsz = 640 project=/content/drive/MyDrive/data/train